import type { Metadata } from "next";
import { Manrope as LoadManrope } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/Navbar";
const DegularDisplay = localFont({
  src: "./DegularDisplay-Regular.woff2",
});

const Manrope = LoadManrope({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        style={{ backgroundColor: "#FFF7F1" }}
        className={`${DegularDisplay.className} ${Manrope.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
